### ISSUE TITLE
Wrong postcondition in example

### ISSUE THREAD

**Issue by valioDOTch** [codemix/contractual#2]
I couldn't help but note that the postcondition in https://github.com/codemix/contractual/blob/master/examples/src/both.js is probably wrong, given the preconditions do not prevent a<=0 or a===NaN or b===NaN or b<0 to be passed to the function. Was that a test? ;-)

**Comment by phpnode** [comment]
@valioDOTch (sorry for the delay) yes you're right, I was never happy with the examples. This module is now deprecated, all the features (and more) are implemented in https://github.com/codemix/babel-plugin-contracts

**Comment by valioDOTch** [comment]
I see...
Thanks for pointing that out and updating the Readme.md ^^
